mod channel_repair;
mod confd;
mod decoder;
pub mod effects;
mod engine;
mod feedback;
pub use feedback::FeedbackSource;
mod envelope;
mod error;
mod handle;
pub mod mixer;
pub mod playback;
pub mod preparation;
pub mod processing;
mod registry;
mod router;
mod routing_graph;
mod store;
pub mod streams;
pub mod voices;

pub use decoder::{DecodedAudio, decode, decode_limited};
pub use effects::{AudioEffect, EffectChain, EffectsCommand, EffectsEvent};
pub use engine::{AudioCommand, AudioEvent, PlayMode, spawn};
pub use envelope::{ENVELOPE_BUCKETS, Envelope};
pub use error::{AudioError, EffectsError, EngineErrorEvent, RouterError, WatcherError};
pub use handle::AudioHandle;
#[cfg(test)]
pub(crate) use handle::test_handle;
pub use router::{AppIdentity, RouteIntent, Router, RouterCommand, RouterEvent};
pub use routing_graph::RouteRejection;
pub use store::{AudioStore, CachedPcm, DEFAULT_PCM_CAP_BYTES};
pub use streams::{Direction, StreamEvent, StreamWatcher};
